import { Injectable, Signal, signal } from '@angular/core';
import { JobApplication } from '../models/job-application';
import { JobApplicationDetails } from '../models/job-application-details';

@Injectable({
  providedIn: 'root'
})
export class JobApplicationService {
  private jobApplications = signal<JobApplication[]>([
    {
      id: '1',
      fullName: 'Ahmed Mostafa',
      industry: 'technology',
      email: 'ahmed.mostafa@example.com',
      englishLevel: 'Advanced',
      phone: '+201234567890',
      currentJobTitle: 'Frontend Developer',
      yearsOfExperience: 3,
      nationality: 'Egyptian',
      submissionCode: 'SUB12345',
      submissionDate: '2025-08-10',
      status: 'reviewed',
    },
    {
      id: '2',
      fullName: 'Sara Ali',
      industry: 'healthcare',
      email: 'sara.ali@example.com',
      englishLevel: 'Intermediate',
      phone: '+201098765432',
      currentJobTitle: 'Nurse',
      yearsOfExperience: 5,
      nationality: 'Egyptian',
      submissionCode: 'SUB67890',
      submissionDate: '2025-08-12',
      status: 'unreviewered',
    },
    {
      id: '3',
      fullName: 'Omar Hassan',
      industry: 'finance',
      email: 'omar.hassan@example.com',
      englishLevel: 'Fluent',
      phone: '+201223344556',
      currentJobTitle: 'Accountant',
      yearsOfExperience: 7,
      nationality: 'Egyptian',
      submissionCode: 'SUB24680',
      submissionDate: '2025-08-14',
      status: 'reviewed',
    },
    {
      id: '4',
      fullName: 'Mona Youssef',
      industry: 'education',
      email: 'mona.youssef@example.com',
      englishLevel: 'Beginner',
      phone: '+201334455667',
      currentJobTitle: 'Teacher',
      yearsOfExperience: 2,
      nationality: 'Egyptian',
      submissionCode: 'SUB13579',
      submissionDate: '2025-08-15',
      status: 'unreviewered',
    },
    {
      id: '5',
      fullName: 'Hassan Ibrahim',
      industry: 'technology',
      email: 'hassan.ibrahim@example.com',
      englishLevel: 'Advanced',
      phone: '+201445566778',
      currentJobTitle: 'Backend Developer',
      yearsOfExperience: 4,
      nationality: 'Egyptian',
      submissionCode: 'SUB11223',
      submissionDate: '2025-08-16',
      status: 'reviewed',
    },
    {
      id: '6',
      fullName: 'Nour Adel',
      industry: 'finance',
      email: 'nour.adel@example.com',
      englishLevel: 'Advanced',
      phone: '+201556677889',
      currentJobTitle: 'Financial Analyst',
      yearsOfExperience: 6,
      nationality: 'Egyptian',
      submissionCode: 'SUB33445',
      submissionDate: '2025-08-17',
      status: 'unreviewered',
    },
    {
      id: '7',
      fullName: 'Youssef Kamal',
      industry: 'technology',
      email: 'youssef.kamal@example.com',
      englishLevel: 'Fluent',
      phone: '+201667788990',
      currentJobTitle: 'Fullstack Developer',
      yearsOfExperience: 5,
      nationality: 'Egyptian',
      submissionCode: 'SUB55667',
      submissionDate: '2025-08-18',
      status: 'reviewed',
    },
    {
      id: '8',
      fullName: 'Layla Mahmoud',
      industry: 'education',
      email: 'layla.mahmoud@example.com',
      englishLevel: 'Intermediate',
      phone: '+201778899001',
      currentJobTitle: 'Lecturer',
      yearsOfExperience: 8,
      nationality: 'Egyptian',
      submissionCode: 'SUB77889',
      submissionDate: '2025-08-19',
      status: 'unreviewered',
    },
    {
      id: '9',
      fullName: 'Khaled Fathy',
      industry: 'healthcare',
      email: 'khaled.fathy@example.com',
      englishLevel: 'Advanced',
      phone: '+201889900112',
      currentJobTitle: 'Pharmacist',
      yearsOfExperience: 3,
      nationality: 'Egyptian',
      submissionCode: 'SUB99001',
      submissionDate: '2025-08-20',
      status: 'reviewed',
    },
    {
      id: '10',
      fullName: 'Reem Tarek',
      industry: 'technology',
      email: 'reem.tarek@example.com',
      englishLevel: 'Beginner',
      phone: '+201990011223',
      currentJobTitle: 'UI/UX Designer',
      yearsOfExperience: 2,
      nationality: 'Egyptian',
      submissionCode: 'SUB11234',
      submissionDate: '2025-08-21',
      status: 'unreviewered',
    },
    {
      id: '11',
      fullName: 'Mostafa Hany',
      industry: 'finance',
      email: 'mostafa.hany@example.com',
      englishLevel: 'Fluent',
      phone: '+201111222333',
      currentJobTitle: 'Auditor',
      yearsOfExperience: 10,
      nationality: 'Egyptian',
      submissionCode: 'SUB22345',
      submissionDate: '2025-08-22',
      status: 'reviewed',
    },
    {
      id: '12',
      fullName: 'Huda Saeed',
      industry: 'education',
      email: 'huda.saeed@example.com',
      englishLevel: 'Intermediate',
      phone: '+201222333444',
      currentJobTitle: 'School Principal',
      yearsOfExperience: 12,
      nationality: 'Egyptian',
      submissionCode: 'SUB33456',
      submissionDate: '2025-08-23',
      status: 'unreviewered',
    },
    {
      id: '13',
      fullName: 'Ali Zaki',
      industry: 'healthcare',
      email: 'ali.zaki@example.com',
      englishLevel: 'Advanced',
      phone: '+201333444555',
      currentJobTitle: 'Surgeon',
      yearsOfExperience: 9,
      nationality: 'Egyptian',
      submissionCode: 'SUB44567',
      submissionDate: '2025-08-24',
      status: 'reviewed',
    },
    {
      id: '14',
      fullName: 'Dina Khalil',
      industry: 'technology',
      email: 'dina.khalil@example.com',
      englishLevel: 'Beginner',
      phone: '+201444555666',
      currentJobTitle: 'QA Tester',
      yearsOfExperience: 1,
      nationality: 'Egyptian',
      submissionCode: 'SUB55678',
      submissionDate: '2025-08-25',
      status: 'unreviewered',
    },
    {
      id: '15',
      fullName: 'Mohamed Farid',
      industry: 'finance',
      email: 'mohamed.farid@example.com',
      englishLevel: 'Fluent',
      phone: '+201555666777',
      currentJobTitle: 'Bank Manager',
      yearsOfExperience: 15,
      nationality: 'Egyptian',
      submissionCode: 'SUB66789',
      submissionDate: '2025-08-26',
      status: 'reviewed',
    },
    {
      id: '16',
      fullName: 'Salma Adel',
      industry: 'education',
      email: 'salma.adel@example.com',
      englishLevel: 'Intermediate',
      phone: '+201666777888',
      currentJobTitle: 'Researcher',
      yearsOfExperience: 4,
      nationality: 'Egyptian',
      submissionCode: 'SUB77890',
      submissionDate: '2025-08-27',
      status: 'unreviewered',
    },
    {
      id: '17',
      fullName: 'Karim Nabil',
      industry: 'technology',
      email: 'karim.nabil@example.com',
      englishLevel: 'Advanced',
      phone: '+201777888999',
      currentJobTitle: 'DevOps Engineer',
      yearsOfExperience: 6,
      nationality: 'Egyptian',
      submissionCode: 'SUB88901',
      submissionDate: '2025-08-28',
      status: 'reviewed',
    },
    {
      id: '18',
      fullName: 'Mai Hassan',
      industry: 'healthcare',
      email: 'mai.hassan@example.com',
      englishLevel: 'Fluent',
      phone: '+201888999000',
      currentJobTitle: 'Dentist',
      yearsOfExperience: 7,
      nationality: 'Egyptian',
      submissionCode: 'SUB99012',
      submissionDate: '2025-08-29',
      status: 'unreviewered',
    },
    {
      id: '19',
      fullName: 'Ibrahim Said',
      industry: 'finance',
      email: 'ibrahim.said@example.com',
      englishLevel: 'Intermediate',
      phone: '+201999000111',
      currentJobTitle: 'Treasury Officer',
      yearsOfExperience: 11,
      nationality: 'Egyptian',
      submissionCode: 'SUB10123',
      submissionDate: '2025-08-30',
      status: 'reviewed',
    },
    {
      id: '20',
      fullName: 'Nadia Gamal',
      industry: 'education',
      email: 'nadia.gamal@example.com',
      englishLevel: 'Beginner',
      phone: '+201000111222',
      currentJobTitle: 'Tutor',
      yearsOfExperience: 1,
      nationality: 'Egyptian',
      submissionCode: 'SUB20234',
      submissionDate: '2025-08-31',
      status: 'unreviewered',
    }
  ])
  private jobApplicationDetails = signal<JobApplicationDetails[]>([
    {
      uid: '1',
      name: 'Ahmed Mostafa',
      title: 'Frontend Developer',
      submittedAt: 'Aug 10, 2025',
      fullName: 'Ahmed Mostafa',
      email: 'ahmed.mostafa@example.com',
      phone: '+201234567890',
      resume: 'AhmedMostafa_Resume.pdf',
      resumeName: 'AhmedMostafa_Resume.pdf',
      portfolio: 'ahmedmostafa.dev',
      linkedin: 'linkedin.com/in/ahmedmostafa',
      yearsOfExperience: 3,
      preferredRole: 'Frontend Developer',
      availability: '2 Weeks',
      salaryExpectations: '$25,000 - $30,000',
      questions: [
        {
          q: 'Why are you interested in this role?',
          a: 'I enjoy building responsive and modern web apps with Angular and React.'
        },
        {
          q: 'What is your availability?',
          a: '2 Weeks'
        },
        {
          q: 'What are your salary expectations?',
          a: '$25,000 - $30,000'
        }
      ]
    },
    {
      uid: '2',
      name: 'Sara Ali',
      title: 'Nurse',
      submittedAt: 'Aug 12, 2025',
      fullName: 'Sara Ali',
      email: 'sara.ali@example.com',
      phone: '+201098765432',
      resume: 'SaraAli_Resume.pdf',
      resumeName: 'SaraAli_Resume.pdf',
      portfolio: 'saraali.com',
      linkedin: 'linkedin.com/in/saraali',
      yearsOfExperience: 5,
      preferredRole: 'Senior Nurse',
      availability: 'Immediately',
      salaryExpectations: '$18,000 - $22,000',
      questions: [
        {
          q: 'Why are you interested in this role?',
          a: 'I am passionate about providing healthcare and helping patients recover.'
        },
        {
          q: 'What is your availability?',
          a: 'Immediately'
        },
        {
          q: 'What are your salary expectations?',
          a: '$18,000 - $22,000'
        }
      ]
    }
  ]);

  getApplications() {
    return this.jobApplications();
  }
  getUserDetails(id: any): JobApplicationDetails | null {
    return this.jobApplicationDetails().find(app => id === app.uid) || null;
  }
}
